AWSTemplateFormatVersion: 2010-09-09
Description: Creates S3 buckets and a Lambda function

Parameters:
  MainBucketName:
    Type: String
    AllowedPattern: '^[a-z0-9\-\.]+$'
    ConstraintDescription: Error naming Bucket. Please see https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
    Description: Enter Bucket Name

  ErrorBucketName:
    Type: String
    AllowedPattern: '^[a-z0-9\-\.]+$'
    ConstraintDescription: Error naming Bucket. Please see https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
    Description: Enter Bucket Name

  AccountId:
    Type: String
    AllowedPattern: '^[0-9]{12}$'
    ConstraintDescription: Please enter a valid AWS Account ID
    Description: Enter AWS Account ID

Resources:
# s3
  MainBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaInvokePermission
    Properties:
      BucketName: !Ref MainBucketName
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
            LambdaConfigurations:
              - Event: s3:ObjectCreated:Put
                Function: !GetAtt LambdaFunction.Arn
                Filter:
                  S3Key:
                    Rules:
                      - Name: suffix
                        Value: .csv
  ErrorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ErrorBucketName
      VersioningConfiguration:
        Status: Enabled

# lambda
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRole
    Properties:
      Timeout: 120
      Handler: lambda.lambda_handler
      Runtime: python3.11
      FunctionName: s3-csv-validation
      Code:
        S3Bucket: resource-bucket-name
        S3Key: lambda/lambda.zip
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AccountId

# iam
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: >-
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Principal": {
                          "Service": "lambda.amazonaws.com"
                      },
                      "Action": "sts:AssumeRole"
                  }
              ]
          }
      Description: Used for Lambda Execution
      Path: /
      Policies: 
       - PolicyDocument: 
           !Sub >-
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Sid": "Statement1",
                        "Effect": "Allow",
                        "Action": [
                            "s3:Put*",
                            "s3:Get*",
                            "s3:List*"
                        ],
                        "Resource": [
                            "arn:aws:s3:::${MainBucketName}",
                            "arn:aws:s3:::${MainBucketName}/*",
                            "arn:aws:s3:::${ErrorBucketName}",
                            "arn:aws:s3:::${ErrorBucketName}/*"
                        ]
                    },
                    {
                        "Sid": "Statement2",
                        "Effect": "Allow",
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                        ],
                        "Resource": "*"
                    }
                ]
            }
         PolicyName: S3AccessPolicy
      RoleName: LambdaExecutionS3AccessRole